name: tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        include:
          - laravel: 10
            php: 8.2
            testbench: ^8.0

          - laravel: 11
            php: 8.2
            testbench: ^9.0

          - laravel: 12
            php: 8.2
            testbench: ^10.0

          - laravel: 13
            php: 8.3
            testbench: ^11.0

          - laravel: 13
            php: 8.5
            testbench: ^11.0

    name: Laravel:${{ matrix.laravel }} PHP:${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, zip, pdo, sqlite, pdo_sqlite
          coverage: pcov

      - name: Select Laravel version
        run: composer require --dev "orchestra/testbench:${{ matrix.testbench }}" --no-update

      - name: Install dependencies
        run: composer update --no-interaction --prefer-dist --no-scripts --with-all-dependencies

      - name: Execute tests
        run: ./vendor/bin/phpunit
